pipeline {
  agent any
  tools {
      maven 'maven3'
    }

  environment {
    PROJECT_DIR = 'SpringBoot_Author_Book_Management'
  }

  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Build') {
      steps {
        dir("${env.PROJECT_DIR}") {
          bat 'mvn -B -DskipTests clean package'
        }
      }
    }

    stage('Test') {
      steps {
        dir("${env.PROJECT_DIR}") {
          bat 'mvn -B test'
        }
      }
      post {
        always {
          junit "${env.PROJECT_DIR}/target/surefire-reports/*.xml"
        }
      }
    }

    stage('Package Artifact') {
      steps {
        dir("${env.PROJECT_DIR}") {
          bat 'dir target'
        }
        archiveArtifacts artifacts: "${env.PROJECT_DIR}/target/*.jar", fingerprint: true
      }
    }
  }
}
